// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jprsirzxfjephinhesay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcnNpcnp4ZmplcGhpbmhlc2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mzg4NTcsImV4cCI6MjA2NTQxNDg1N30.vc-X2Z7D6MUsMqt6z4QPSWWJw5D0YS6lVILMASwCahQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);